apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hkmkzfg9k-python 
  janus-idp.io/tekton: hkmkzfg9k-python
  backstage.io/kubernetes-id: hkmkzfg9k-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hkmkzfg9k-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  